"use client";

import { useSearchParams } from "next/navigation";
import { DownloadSimple, FloppyDisk, Function as FunctionIcon, Lightning, ShoppingCartSimple, TreeStructure } from "@phosphor-icons/react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useCallback, useEffect, useMemo, useState } from "react";
import { PageHeader } from "@/components/shell/AppShell";
import { useShortcutActions } from "@/components/shortcuts/ShortcutProvider";
import { Badge, Button, Card, CardBody, CardHeader, ErrorMessage, Field, Input, NativeSelect, Notice, uiStyles } from "@/components/ui";
import { usePrestigeProfiles } from "@/lib/client/prestige-profiles";
import { shoppingListToCsv } from "@/lib/crafting";
import { NumberValue } from "@/components/ui/NumberValue";
import type { CatalogItem, CraftRequest, CraftResult, CraftTreeNode } from "@/lib/types";
import shared from "@/app/pages.module.css";
import styles from "./CraftLab.module.css";

async function fetchItems() { const response = await fetch("/api/items"); return response.json() as Promise<{ items: CatalogItem[] }>; }
function download(name: string, content: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }

export function CraftLab() {
  const searchParams = useSearchParams(); const queryClient = useQueryClient(); const { profiles } = usePrestigeProfiles();
  const itemsQuery = useQuery({ queryKey: ["items"], queryFn: fetchItems });
  const craftable = useMemo(() => (itemsQuery.data?.items ?? []).filter((item) => item.craftable), [itemsQuery.data]);
  const [idName, setIdName] = useState(searchParams.get("item") ?? ""); const [targetMode, setTargetMode] = useState<"quantity" | "budget">("quantity"); const [quantity, setQuantity] = useState("1"); const [recipeMode, setRecipeMode] = useState<CraftRequest["recipeMode"]>("optimized"); const [priceMode, setPriceMode] = useState<CraftRequest["priceMode"]>("lowest"); const [profileId, setProfileId] = useState("main"); const [salePrice, setSalePrice] = useState(searchParams.get("salePrice") ?? ""); const [budget, setBudget] = useState(""); const [overrides, setOverrides] = useState<Record<string, string>>({}); const [planName, setPlanName] = useState("");
  const [resultInputKey, setResultInputKey] = useState<string | null>(null);
  const [editablePrices, setEditablePrices] = useState<{ idName: string; ids: string[] }>({ idName: "", ids: [] });
  const selectedProfile = profiles.find((entry) => entry.id === profileId) ?? profiles[0];
  const inputKey = JSON.stringify([idName, targetMode, quantity, recipeMode, priceMode, selectedProfile, salePrice, budget, overrides]);
  useEffect(() => { if (!idName && craftable[0]) setIdName(craftable[0].idName); }, [craftable, idName]);
  useEffect(() => { if (!profiles.some((profile) => profile.id === profileId) && profiles[0]) setProfileId(profiles[0].id!); }, [profiles, profileId]);
  const calculation = useMutation({ mutationFn: async ({ request }: { request: CraftRequest; key: string }) => { const response = await fetch("/api/craft/calculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(request) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Calculation failed."); return body as { request: CraftRequest; result: CraftResult }; }, onSuccess: (data, variables) => { setResultInputKey(variables.key); setEditablePrices({ idName: data.request.idName, ids: [...new Set([...data.result.missingPrices, ...Object.keys(data.result.orderBookUnfilled)])] }); } });
  const currentCalculation = calculation.isSuccess && resultInputKey === inputKey ? calculation.data : undefined;
  const result = currentCalculation?.result;
  const manualPriceIds = [...new Set([...(editablePrices.idName === idName ? editablePrices.ids : []), ...Object.keys(overrides)])];
  const save = useMutation({ mutationFn: async () => { if (!currentCalculation) throw new Error("Calculate a plan for the current inputs first."); const response = await fetch("/api/plans", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: planName || `${currentCalculation.result.target.name} × ${currentCalculation.result.target.quantity}`, payload: { ...currentCalculation.request, marketSnapshotAt: currentCalculation.result.marketSnapshotAt }, result: currentCalculation.result }) }); if (!response.ok) throw new Error("Plan could not be saved."); return response.json(); }, onSuccess: () => { setPlanName(""); void queryClient.invalidateQueries({ queryKey: ["plans"] }); } });
  const run = useCallback(() => { if (calculation.isPending || !selectedProfile) return; const request: CraftRequest = { idName, targetMode, quantity: targetMode === "quantity" ? quantity : "1", recipeMode, priceMode, profile: { ...selectedProfile, capturedAt: new Date().toISOString() }, manualPriceOverrides: overrides, salePrice: salePrice || undefined, budget: targetMode === "budget" ? budget : undefined }; calculation.mutate({ request, key: inputKey }); }, [calculation, selectedProfile, idName, targetMode, quantity, recipeMode, priceMode, overrides, salePrice, budget, inputKey]);
  const savePlan = useCallback(() => { if (result && !save.isPending) save.mutate(); }, [result, save]);
  const shortcutActions = useMemo(() => ({ calculate: run, save: result ? savePlan : undefined }), [result, run, savePlan]);
  useShortcutActions(shortcutActions);
  return <>
    <PageHeader title="Craft Lab" description="Find the cheapest mix of market purchases and recursive crafting." />
    <div className={styles.workbench}>
      <Card><CardHeader title="Calculation inputs" description="Quantities use exact whole-number arithmetic" /><CardBody><div className={styles.formGrid}>
        <Field label="Output item"><NativeSelect value={idName} onChange={(e) => setIdName(e.target.value)}>{craftable.map((item) => <option value={item.idName} key={item.idName}>{item.name}</option>)}</NativeSelect></Field>
        <fieldset className={styles.controlGroup}><legend>Target</legend><div className={styles.segment} style={{ gridTemplateColumns: "repeat(2, 1fr)" }}>{(["quantity", "budget"] as const).map((mode) => <button type="button" className={targetMode === mode ? styles.active : ""} key={mode} onClick={() => setTargetMode(mode)}>{mode === "quantity" ? "Quantity" : "Budget"}</button>)}</div></fieldset>
        {targetMode === "quantity"
          ? <Field label="Quantity" help="Examples: 25k, 2.5 million, (10 + 5) * 3"><Input name="craft-quantity" value={quantity} onChange={(e) => setQuantity(e.target.value)} inputMode="text" /></Field>
          : <Field label="Budget" help="Maximum BC to spend; examples: 5.11t or 5.11 trillion"><Input name="craft-budget" value={budget} onChange={(e) => setBudget(e.target.value)} inputMode="text" placeholder="e.g. 5.11t…" /></Field>}
        <fieldset className={styles.controlGroup}><legend>Plan</legend><div className={styles.segment}>{(["direct", "recursive", "optimized"] as const).map((mode) => <button type="button" className={recipeMode === mode ? styles.active : ""} key={mode} onClick={() => setRecipeMode(mode)}>{mode === "direct" ? <Lightning /> : mode === "recursive" ? <TreeStructure /> : <FunctionIcon />} {mode === "direct" ? "Direct" : mode === "recursive" ? "Craft all" : "Lowest cost"}</button>)}</div></fieldset>
        <fieldset className={styles.controlGroup}><legend>Cost model</legend><div className={styles.segment} style={{ gridTemplateColumns: "repeat(2, 1fr)" }}>{(["lowest", "orderbook"] as const).map((mode) => <button type="button" className={priceMode === mode ? styles.active : ""} key={mode} onClick={() => setPriceMode(mode)}>{mode === "lowest" ? "Lowest listing" : "Order-book depth"}</button>)}</div></fieldset>
        <Field label="Prestige profile"><NativeSelect value={profileId} onChange={(e) => setProfileId(e.target.value)}>{profiles.map((profile) => <option value={profile.id} key={profile.id}>{profile.name}</option>)}</NativeSelect></Field>
        <Field label="Custom output sale price" help="Optional; accepts 125k or 2.5 million. Defaults to the last saved market price."><Input name="sale-price" value={salePrice} onChange={(e) => setSalePrice(e.target.value)} placeholder="e.g. 125k…" /></Field>
        {manualPriceIds.length ? <div className={styles.formGrid}><Notice>Missing prices keep totals as incomplete lower bounds. Add overrides to complete this plan. Clear an override to use market prices again.</Notice>{manualPriceIds.map((missing) => <div className={styles.overrideRow} key={missing}><span>{itemsQuery.data?.items.find((item) => item.idName === missing)?.name ?? missing}</span><Input name={`manual-price-${missing}`} aria-label={`Manual price for ${missing}`} placeholder="e.g. 125…" value={overrides[missing] ?? ""} onChange={(e) => setOverrides((current) => { const next = { ...current }; if (e.target.value.trim()) next[missing] = e.target.value; else delete next[missing]; return next; })} /></div>)}</div> : null}
        {calculation.error && <ErrorMessage>{calculation.error.message}</ErrorMessage>}
        <Button variant="primary" aria-keyshortcuts="Control+Enter" title="Calculate (Ctrl+Enter)" disabled={!idName || calculation.isPending || (targetMode === "budget" ? !budget.trim() : !quantity.trim())} onClick={run}><CirclesIcon />{calculation.isPending ? "Calculating…" : targetMode === "budget" ? "Build from budget" : recipeMode === "optimized" ? "Find lowest cost" : "Calculate plan"}</Button>
      </div></CardBody></Card>
      <div className={styles.results}>
        {calculation.data && resultInputKey !== inputKey && <Notice>Inputs changed. Calculate again to update the plan and its costs.</Notice>}
        {result?.budget && <BudgetSummary result={result} />}
        {result?.recommendation && <Recommendation result={result} />}
        <Card><CardHeader title="Recipe circuit" description={result ? <>{result.recipeMode} path · <NumberValue value={result.target.quantity} /> outputs</> : "Craft and buy paths appear as an electrical trace"} action={result && <div className={shared.chipRow}><Badge tone="positive">Buy</Badge><Badge>Craft</Badge><Badge>Mix</Badge><Badge tone="warning">Raw / missing</Badge></div>} /><CardBody className={styles.circuitPanel}>{result ? <RecipeCircuit tree={result.tree} /> : <div className={uiStyles.empty}>Choose an item and calculate to energize the circuit.</div>}</CardBody></Card>
        {result && <>
          {!result.complete && <Notice>{result.unfilledQuantity && BigInt(result.unfilledQuantity) > 0n ? <><NumberValue value={result.fulfilledQuantity ?? "0"} />{" of "}<NumberValue value={result.target.quantity} />{" can be fulfilled. "}<NumberValue value={result.unfilledQuantity} />{" remain unfilled."}</> : "This is an incomplete lower bound because one or more materials have no usable price."}</Notice>}
          <div className={styles.summary}><Summary label={result.shoppingList.some((line) => line.lowestCost === null) || (!result.complete && result.shoppingList.length === 0) ? "Lowest known subtotal" : "Lowest estimate"} value={<NumberValue value={result.knownLowestTotal} unit="BC" />} /><Summary label="Order-book known" value={<NumberValue value={result.knownOrderBookTotal} unit="BC" />} /><Summary label={result.complete ? "Selected total" : "Selected known subtotal"} value={<NumberValue value={result.selectedKnownTotal} unit="BC" />} /><Summary label="Market preview snapshot" value={result.marketSnapshotAt ? new Date(result.marketSnapshotAt).toLocaleString() : "No snapshot"} /></div>
          {result.decisions?.length ? <Card><CardHeader title="Build plan" description="Exact quantities selected across the full recipe" /><CardBody className={uiStyles.tableWrap}><table className={uiStyles.table}><thead><tr><th>Item</th><th>Needed</th><th>Buy</th><th>Craft</th><th>Buy cost</th></tr></thead><tbody>{result.decisions.map((decision) => <tr key={decision.idName}><td>{decision.name}</td><td className={uiStyles.number}><NumberValue value={decision.requiredQuantity} /></td><td className={uiStyles.number}><NumberValue value={decision.buyQuantity} /></td><td className={uiStyles.number}><NumberValue value={decision.craftQuantity} /></td><td className={uiStyles.number}><NumberValue value={decision.buyCost} unit="BC" />{BigInt(decision.unfilledQuantity) > 0n && <div className="negative"><NumberValue value={decision.unfilledQuantity} /> unfilled</div>}</td></tr>)}</tbody></table></CardBody></Card> : null}
          <Card><CardHeader title="Consolidated shopping list" description="Ingredients are combined before order-book repricing" action={<div className={shared.actions}><Button size="small" onClick={() => download("ascendry-shopping-list.csv", shoppingListToCsv(result), "text/csv")}><DownloadSimple />CSV</Button><Button size="small" onClick={() => download("ascendry-plan.json", JSON.stringify({ schemaVersion: 1, plans: [{ name: planName.trim() || `${result.target.name} × ${result.target.quantity}`, payload: { ...currentCalculation!.request, marketSnapshotAt: result.marketSnapshotAt }, result }] }, null, 2), "application/json")}><DownloadSimple />JSON</Button></div>} /><CardBody className={uiStyles.tableWrap}><table className={uiStyles.table}><thead><tr><th>Material</th><th>Quantity</th><th>Decision</th><th>Unit price</th><th>Subtotal</th><th>Cost share</th></tr></thead><tbody>{result.shoppingList.map((line) => <tr key={line.idName}><td>{line.name}</td><td className={uiStyles.number}><NumberValue value={line.quantity} /></td><td><Badge tone={line.decision === "buy" ? "positive" : "warning"}>{line.decision}</Badge></td><td className={uiStyles.number}>{line.unitPrice ? <NumberValue value={line.unitPrice} unit="BC" /> : "Missing"}</td><td className={uiStyles.number}><NumberValue value={(result.priceMode === "orderbook" ? line.orderBookCost : line.lowestCost) ?? "0"} unit="BC" />{BigInt(line.unfilledQuantity) > 0n && <div className="negative"><NumberValue value={line.unfilledQuantity} /> unfilled</div>}</td><td className={uiStyles.number}>{line.percentOfKnownCost.toFixed(1)}%</td></tr>)}</tbody></table></CardBody></Card>
          <div className={`${shared.grid} ${shared.twoColumns}`}>
            <Card><CardHeader title="Pareto cost load" description="Largest material costs first" /><CardBody><div className={shared.chart}><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={result.shoppingList.slice(0, 8)} margin={{ left: 12 }}><CartesianGrid stroke="var(--border)" strokeOpacity={.25} horizontal={false}/><XAxis type="number" tickFormatter={(v) => `${v}%`} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }}/><YAxis type="category" dataKey="name" width={110} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }}/><Tooltip formatter={(value) => `${Number(value).toFixed(1)}%`} contentStyle={{ background: "var(--card-strong)", border: "1px solid var(--border)", borderRadius: 8 }}/><Bar dataKey="percentOfKnownCost" fill="var(--chart-1)" radius={[0, 4, 4, 0]}/></BarChart></ResponsiveContainer></div></CardBody></Card>
            <Card><CardHeader title="Profitability" description={result.profitability.hypothetical ? "Hypothetical: output is locked by Mercantilist" : "After current Insider fee"} /><CardBody><p className={styles.numberHint}>Shortened amounts are rounded. Hover, focus, or tap a dotted value for the exact amount.</p><div className={shared.kpiLine}><Kpi label="Gross" value={money(result.profitability.gross)} /><Kpi label={`Fee (${(result.profitability.feeBps / 100).toFixed(1)}%)`} value={money(result.profitability.fee)} /><Kpi label="Net" value={money(result.profitability.net)} /><Kpi label="Material cost" value={money(result.profitability.materialCost)} /><Kpi label="Profit" value={money(result.profitability.profit)} /><Kpi label="Break-even" value={money(result.profitability.breakEvenListingPrice)} /></div><div className={`${shared.chipRow} ${shared.sectionGap}`}><Badge tone={result.profitability.profit && BigInt(result.profitability.profit) >= 0n ? "positive" : "negative"}>ROI {result.profitability.roiPercent?.toFixed(2) ?? "—"}%</Badge><Badge>Margin {result.profitability.marginPercent?.toFixed(2) ?? "—"}%</Badge><Badge tone={result.profitability.eligibleToSell ? "positive" : "warning"}>Requires Mercantilist {result.profitability.requiredMercantilistLevel ?? "—"}</Badge></div></CardBody></Card>
          </div>
          <Card><CardHeader title="Save this scenario" description="The plan stores this exact Prestige profile and market timestamp" /><CardBody><div className={styles.saveBar}><Field label="Plan name"><Input name="plan-name" value={planName} onChange={(e) => setPlanName(e.target.value)} placeholder={`${result.target.name} × ${result.target.quantity}…`} /></Field><Button variant="primary" aria-keyshortcuts="Control+Shift+S" title="Save plan (Ctrl+Shift+S)" disabled={save.isPending} onClick={savePlan}><FloppyDisk />{save.isSuccess ? "Saved" : "Save plan"}</Button></div>{save.error && <ErrorMessage>{save.error.message}</ErrorMessage>}</CardBody></Card>
        </>}
      </div>
    </div>
  </>;
}

function CirclesIcon() { return <ShoppingCartSimple />; }
function Recommendation({ result }: { result: CraftResult }) {
  const label = result.recommendation === "buy" ? "Buy" : result.recommendation === "craft" ? "Craft" : result.recommendation === "mix" ? "Mix" : "Unavailable";
  return <section className={styles.recommendation} aria-label="Lowest-cost recommendation" aria-live="polite"><div><span className={styles.recommendationLabel}>Best option</span><strong>{label}</strong><p>{result.recommendationSummary}</p></div><div className={styles.recommendationMetrics}><Summary label={result.complete ? "Total cost" : "Known cost"} value={<NumberValue value={result.selectedKnownTotal} unit="BC" />} /><Summary label="Save vs buy" value={result.savingsVsBuy === null || result.savingsVsBuy === undefined ? "—" : <NumberValue value={result.savingsVsBuy} unit="BC" />} /><Summary label="Save vs craft" value={result.savingsVsCraft === null || result.savingsVsCraft === undefined ? "—" : <NumberValue value={result.savingsVsCraft} unit="BC" />} /></div></section>;
}
function Summary({ label, value }: { label: string; value: React.ReactNode }) { return <div className={styles.summaryCell}><span>{label}</span><strong>{value}</strong></div>; }
function Kpi({ label, value }: { label: string; value: React.ReactNode }) { return <div className={shared.kpi}><span>{label}</span><strong>{value}</strong></div>; }
function BudgetSummary({ result }: { result: CraftResult }) { const budget = result.budget!; const note = budget.limitingFactor === "market-depth" ? "Limited by available listings" : budget.limitingFactor === "unknown-supply" ? "Maximum is incomplete because supply is unknown" : budget.nextUnitShortfall ? <>{"Next item needs "}<NumberValue value={budget.nextUnitShortfall} />{" more BC"}</> : "Maximum complete output within budget"; return <section className={styles.budgetSummary} aria-label="Budget result" aria-live="polite"><div className={styles.budgetHeading}><span>Budget result</span><strong>{note}</strong></div><div className={styles.budgetMetrics}><Summary label="Items produced" value={<NumberValue value={result.target.quantity} />} /><Summary label="Spent" value={<NumberValue value={budget.spent} unit="BC" />} /><Summary label="Unspent" value={<NumberValue value={budget.unspent} unit="BC" />} /><Summary label="Average cost" value={budget.averageUnitCost === null ? "—" : <NumberValue value={budget.averageUnitCost} unit="BC" />} /></div></section>; }
function money(value: string | null) { return value === null ? "Incomplete" : <NumberValue value={value} unit="BC" />; }
function RecipeCircuit({ tree }: { tree: CraftTreeNode }) { return <div className={styles.circuit}><Tree node={tree} /></div>; }
function Tree({ node }: { node: CraftTreeNode }) { return <ul><li><NodeCard node={node} />{node.children.length > 0 && <TreeChildren nodes={node.children} />}</li></ul>; }
function TreeChildren({ nodes }: { nodes: CraftTreeNode[] }) { return <ul>{nodes.map((node) => <li key={`${node.idName}-${node.quantity}`}><NodeCard node={node} />{node.children.length > 0 && <TreeChildren nodes={node.children} />}</li>)}</ul>; }
function NodeCard({ node }: { node: CraftTreeNode }) { const hasSplit = node.buyQuantity !== undefined || node.craftQuantity !== undefined; return <div className={`${styles.node} ${styles[node.action]}`}><div className={styles.nodeTop}><span className={styles.nodeName}>{node.name}</span><span className={styles.nodeAction}>{node.action}</span></div><span className={styles.nodeQuantity}>Need <NumberValue value={node.quantity} /></span>{hasSplit && <span className={styles.nodeQuantity}>Buy <NumberValue value={node.buyQuantity ?? "0"} /> · Craft <NumberValue value={node.craftQuantity ?? "0"} /></span>}{node.unfilledQuantity && BigInt(node.unfilledQuantity) > 0n && <span className={styles.nodeMissing}><NumberValue value={node.unfilledQuantity} /> unfilled</span>}{node.subtotal && <span className={styles.nodeQuantity}><NumberValue value={node.subtotal} unit="BC" /></span>}</div>; }
