"use client";

import { ArrowsClockwise, Copy, DownloadSimple, Trash, UploadSimple } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRef, useState } from "react";
import { PageHeader } from "@/components/shell/AppShell";
import { Badge, Button, Card, CardBody, CardHeader, ErrorMessage, Notice, uiStyles } from "@/components/ui";
import { usePrestigeProfiles } from "@/lib/client/prestige-profiles";
import { NumberValue } from "@/components/ui/NumberValue";
import { parsePlanImport } from "@/lib/plan-schema";
import { assertResponseOk } from "@/lib/client/http";
import type { SavedPlan } from "@/lib/types";
import styles from "@/app/pages.module.css";

async function getPlans() { const response = await fetch("/api/plans"); await assertResponseOk(response, "Plans could not be loaded."); return response.json() as Promise<{ plans: SavedPlan[] }>; }
function download(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }

export function PlansWorkspace() {
  const client = useQueryClient(); const plans = useQuery({ queryKey: ["plans"], queryFn: getPlans }); const { profiles } = usePrestigeProfiles(); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const fileRef = useRef<HTMLInputElement>(null);
  const remove = useMutation({ mutationFn: async (id: string) => { const response = await fetch(`/api/plans/${id}`, { method: "DELETE" }); await assertResponseOk(response, "Plan could not be deleted."); }, onSuccess: (_data, id) => { setError(null); setSelected((current) => current.filter((entry) => entry !== id)); void client.invalidateQueries({ queryKey: ["plans"] }); }, onError: (cause) => setError(cause.message) });
  const action = useMutation({ mutationFn: (perform: () => Promise<void>) => perform(), onSuccess: () => setError(null), onError: (cause) => setError(cause.message) });
  const persist = async (plan: Pick<SavedPlan, "name" | "payload" | "result">) => { const response = await fetch("/api/plans", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(plan) }); await assertResponseOk(response, "Plan could not be saved."); void client.invalidateQueries({ queryKey: ["plans"] }); };
  const duplicate = async (plan: SavedPlan) => { await persist({ name: `${plan.name} copy`, payload: plan.payload, result: plan.result }); };
  const recalc = async (plan: SavedPlan) => { const current = profiles.find((profile) => profile.id === plan.payload.profile.id) ?? profiles[0]; if (!current) throw new Error("No current Prestige profile exists."); const response = await fetch("/api/craft/calculate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...plan.payload, profile: current }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Recalculation failed."); await persist({ name: `${plan.name} · current perks`, payload: { ...data.request, marketSnapshotAt: data.result.marketSnapshotAt }, result: data.result }); };
  const imported = async (file: File) => { const incoming = parsePlanImport(JSON.parse(await file.text()) as unknown); for (const plan of incoming) await persist(plan); };
  const compared = (plans.data?.plans ?? []).filter((plan) => selected.includes(plan.id));
  return <>
    <PageHeader title="Scenario plans" description="Keep unlimited named calculations, preserve their original assumptions, and compare up to four side by side." action={<div className={styles.actions}><Button onClick={() => download("ascendry-plans.json", JSON.stringify({ schemaVersion: 1, plans: plans.data?.plans ?? [] }, null, 2))}><DownloadSimple />Export all</Button><Button disabled={action.isPending} onClick={() => fileRef.current?.click()}><UploadSimple />Import</Button><input ref={fileRef} aria-label="Choose plan file" name="plan-file" hidden type="file" accept="application/json,.json" onChange={(e) => { const file = e.target.files?.[0]; if (file) action.mutate(() => imported(file)); }} /></div>} />
    {(error || plans.error) && <ErrorMessage>{error || plans.error?.message}</ErrorMessage>}
    {compared.length > 0 && <Card><CardHeader title="Comparison rail" description={`${compared.length} of 4 selected`} /><CardBody className={uiStyles.tableWrap}><table className={uiStyles.table}><thead><tr><th>Plan</th><th>Output</th><th>Mode</th><th>Known cost</th><th>Profit</th><th>Profile snapshot</th></tr></thead><tbody>{compared.map((plan) => <tr key={plan.id}><td>{plan.name}</td><td>{plan.result.target.name} × <NumberValue value={plan.result.target.quantity} /></td><td>{plan.result.recipeMode} / {plan.result.priceMode}</td><td className={uiStyles.number}><NumberValue value={plan.result.selectedKnownTotal} unit="BC" /></td><td className={uiStyles.number}>{plan.result.profitability.profit === null ? "Incomplete" : <NumberValue value={plan.result.profitability.profit} unit="BC" />}</td><td>{plan.payload.profile.name}</td></tr>)}</tbody></table></CardBody></Card>}
    <div className={`${styles.grid} ${styles.threeColumns} ${styles.sectionGap}`}>{plans.data?.plans.map((plan) => <Card key={plan.id}><CardHeader title={plan.name} description={`${new Date(plan.updatedAt).toLocaleString()} · ${plan.payload.profile.name}`} action={<input type="checkbox" aria-label={`Compare ${plan.name}`} checked={selected.includes(plan.id)} onChange={(e) => setSelected((current) => e.target.checked ? current.length < 4 ? [...current, plan.id] : current : current.filter((id) => id !== plan.id))} />} /><CardBody><div className={styles.stack}><div className={styles.row}><span>{plan.result.target.name}</span><Badge>× <NumberValue value={plan.result.target.quantity} /></Badge></div><div className={styles.kpiLine}><div className={styles.kpi}><span>Known cost</span><strong><NumberValue value={plan.result.selectedKnownTotal} /></strong></div><div className={styles.kpi}><span>Profit</span><strong>{plan.result.profitability.profit === null ? "—" : <NumberValue value={plan.result.profitability.profit} />}</strong></div><div className={styles.kpi}><span>Snapshot</span><strong>{plan.result.marketSnapshotAt ? new Date(plan.result.marketSnapshotAt).toLocaleDateString() : "—"}</strong></div></div>{!plan.result.complete && <Notice>Incomplete lower-bound result</Notice>}<div className={styles.actions}><Button size="small" disabled={action.isPending} onClick={() => action.mutate(() => duplicate(plan))}><Copy />Duplicate</Button><Button size="small" disabled={action.isPending} onClick={() => action.mutate(() => recalc(plan))}><ArrowsClockwise />Current perks</Button><Button size="small" variant="danger" disabled={remove.isPending || action.isPending} onClick={() => { if (window.confirm(`Delete ${plan.name}?`)) remove.mutate(plan.id); }}><Trash />Delete</Button></div></div></CardBody></Card>)}</div>
    {!plans.isLoading && !plans.data?.plans.length && <Card className={styles.sectionGap}><div className={uiStyles.empty}>No saved plans yet. Build one in Craft Lab.</div></Card>}
  </>;
}
