"use client";

import Link from "next/link";
import { Bell, CirclesThreePlus, ShoppingCartSimple } from "@phosphor-icons/react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { PageHeader } from "@/components/shell/AppShell";
import { Badge, Button, Card, CardBody, CardHeader, ErrorMessage, Field, Input, NativeSelect, Notice, uiStyles } from "@/components/ui";
import { NumberValue } from "@/components/ui/NumberValue";
import { formatInteger, parseQuantityExpression } from "@/lib/quantity";
import type { CatalogItem, MarketListing } from "@/lib/types";
import styles from "@/app/pages.module.css";

interface ItemResponse { item: CatalogItem; uses: Array<{ idName: string; name: string }>; localHistory: Array<{ snapshotTime: string; lowestPrice: string | null; source: string }> }
interface MarketResponse { listings: MarketListing[]; transactions: Array<{ type: string; actorName: string; amount: string; price: string; date: string }>; priceHistory: Array<{ snapshotTime: string; lowestPrice: string | null; source: string }>; volumeHistory: Array<{ windowStart: string; unitsSold: string; totalRevenue: string; transactionCount: string }>; cached: boolean }
async function fetchJson<T>(url: string): Promise<T> { const response = await fetch(url); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Data could not be loaded."); return body as T; }

export function ItemDetail({ idName }: { idName: string }) {
  const queryClient = useQueryClient();
  const itemQuery = useQuery({ queryKey: ["item", idName], queryFn: () => fetchJson<ItemResponse>(`/api/items/${encodeURIComponent(idName)}`) });
  const marketQuery = useQuery({ queryKey: ["item-market", idName], queryFn: () => fetchJson<MarketResponse>(`/api/items/${encodeURIComponent(idName)}/market?days=90`) });
  const [direction, setDirection] = useState<"below" | "above">("below"); const [threshold, setThreshold] = useState(""); const [targetPrice, setTargetPrice] = useState("");
  const alert = useMutation({ mutationFn: async () => { const value = parseQuantityExpression(threshold).toString(); const response = await fetch("/api/watchlist", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idName, direction, threshold: value, enabled: true }) }); if (!response.ok) throw new Error("Alert could not be saved."); }, onSuccess: () => { setThreshold(""); void queryClient.invalidateQueries({ queryKey: ["alerts"] }); } });
  if (itemQuery.isLoading) return <div className={uiStyles.empty}>Loading item…</div>;
  if (itemQuery.error || !itemQuery.data) return <ErrorMessage>{itemQuery.error?.message ?? "Item not found."}</ErrorMessage>;
  const { item, uses } = itemQuery.data;
  const history = marketQuery.data?.priceHistory ?? itemQuery.data.localHistory;
  const chartData = history.filter((point) => point.lowestPrice !== null).map((point) => ({ date: new Date(point.snapshotTime).toLocaleDateString(undefined, { month: "short", day: "numeric" }), price: Number(point.lowestPrice), exactPrice: point.lowestPrice! }));
  const volumeData = (marketQuery.data?.volumeHistory ?? []).map((point) => ({ date: new Date(point.windowStart).toLocaleDateString(undefined, { month: "short", day: "numeric" }), units: Number(point.unitsSold), exactUnits: point.unitsSold }));
  const approximatePriceChart = chartData.some((point) => !Number.isSafeInteger(point.price));
  const approximateVolumeChart = volumeData.some((point) => !Number.isSafeInteger(point.units));
  return <>
    <PageHeader title={`${item.emoji} ${item.name}`} description={<>{item.idName}{" · base value "}<NumberValue value={item.baseValue} />{" BC"}</>} action={<Link className={`${uiStyles.button} ${uiStyles.primary}`} href={`/craft?item=${item.idName}`}><CirclesThreePlus />Craft this item</Link>} />
    <div className={`${styles.grid} ${styles.metrics}`}>
      <Metric label="Lowest listing" value={item.market?.price ? <NumberValue value={item.market.price} unit="BC" /> : "Unpriced"} meta={item.market?.snapshotAt ? new Date(item.market.snapshotAt).toLocaleString() : "No market snapshot"} />
      <Metric label="24-hour change" value={item.market?.delta.day === null || item.market?.delta.day === undefined ? "—" : `${item.market.delta.day >= 0 ? "+" : ""}${item.market.delta.day.toFixed(2)}%`} meta="Market preview delta" />
      <Metric label="Crafting" value={item.craftable ? `${item.recipe.length} inputs` : "No recipe"} meta={`${uses.length} reverse uses`} />
      <Metric label="Sell access" value={item.mercantilistLevel === null ? "Not listed" : `Mercantilist ${item.mercantilistLevel}`} meta={item.mercantilistLevel === 0 ? "Baseline access" : "Normal profile"} />
    </div>
    <div className={`${styles.grid} ${styles.twoColumns} ${styles.sectionGap}`}>
      <Card><CardHeader title="Price history" description="Official history merged with unique local manual snapshots" action={marketQuery.data && <Badge>Loaded</Badge>} /><CardBody>{chartData.length ? <div className={styles.chart}><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--chart-1)" stopOpacity={0.32}/><stop offset="95%" stopColor="var(--chart-1)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" strokeOpacity={0.28} vertical={false}/><XAxis dataKey="date" tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} /><YAxis tickFormatter={(value) => formatInteger(BigInt(Math.round(value)), true)} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} width={60}/><Tooltip formatter={(_value, _name, entry) => `${formatInteger(String(entry.payload.exactPrice))} BC`} contentStyle={{ background: "var(--card-strong)", border: "1px solid var(--border)", borderRadius: 8 }}/><Area type="monotone" dataKey="price" stroke="var(--chart-1)" fill="url(#priceFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div> : <div className={uiStyles.empty}>No price history is available yet.</div>}{approximatePriceChart && <Notice>Chart positions are approximate at this scale; hover values show the exact prices.</Notice>}{marketQuery.error && <ErrorMessage>{marketQuery.error.message} Local history is still shown.</ErrorMessage>}</CardBody></Card>
      <div className={styles.stack}>
        <Card><CardHeader title="Price alert" description="Checked after your next manual refresh" /><CardBody><div className={styles.stack}><div className={styles.inline}><NativeSelect name="alert-direction" aria-label="Alert direction" value={direction} onChange={(e) => setDirection(e.target.value as "below" | "above")}><option value="below">At or below</option><option value="above">At or above</option></NativeSelect><Input name="alert-threshold" aria-label="Alert price" value={threshold} onChange={(e) => setThreshold(e.target.value)} placeholder="e.g. 25k…" /></div>{alert.error && <ErrorMessage>{alert.error.message}</ErrorMessage>}<Button variant="primary" disabled={!threshold || alert.isPending} onClick={() => alert.mutate()}><Bell />Save alert</Button></div></CardBody></Card>
        <Card><CardHeader title="Custom target price" description="Carry a manual output price into a new profitability plan" /><CardBody><div className={styles.stack}><Field label="Target listing price"><Input name="item-target-price" value={targetPrice} onChange={(event) => setTargetPrice(event.target.value)} placeholder="e.g. 125k…" /></Field>{targetPrice ? <Link className={uiStyles.button} href={`/craft?item=${encodeURIComponent(item.idName)}&salePrice=${encodeURIComponent(targetPrice)}`}><CirclesThreePlus />Open priced plan</Link> : <p className="mutedText">Enter a whole-number expression to prepare a custom plan.</p>}</div></CardBody></Card>
        <Card><CardHeader title="Recipe" description={item.craftable ? "Direct ingredients" : "This item cannot be crafted"} /><CardBody>{item.recipe.length ? <div className={styles.dividerRows}>{item.recipe.map((ingredient) => <Link className={`${styles.row} ${styles.listRow}`} href={`/items/${ingredient.ingredientIdName}`} key={ingredient.ingredientIdName}><span>{ingredient.ingredientName}</span><span className="mono">× <NumberValue value={ingredient.amount} interactive={false} /></span></Link>)}</div> : <div className={uiStyles.empty}>No crafting recipe.</div>}</CardBody></Card>
      </div>
    </div>
    <div className={`${styles.grid} ${styles.twoColumns} ${styles.sectionGap}`}>
      <Card><CardHeader title="Order book" description="Up to 50 active listings, cheapest first" /><CardBody className={uiStyles.tableWrap}>{marketQuery.data?.listings.length ? <table className={uiStyles.table}><thead><tr><th>Seller BcID</th><th>Amount</th><th>Unit price</th><th>Listing total</th></tr></thead><tbody>{marketQuery.data.listings.map((listing) => <tr key={listing.id}><td className="mono">#{listing.bcId}</td><td className={uiStyles.number}><NumberValue value={listing.amount} /></td><td className={uiStyles.number}><NumberValue value={listing.price} unit="BC" /></td><td className={uiStyles.number}><NumberValue value={BigInt(listing.price) * BigInt(listing.amount)} unit="BC" /></td></tr>)}</tbody></table> : <div className={uiStyles.empty}><ShoppingCartSimple size={24} />No live listings loaded.</div>}</CardBody></Card>
      <Card><CardHeader title="Used to craft" description="Every recipe that consumes this item" /><CardBody>{uses.length ? <div className={styles.dividerRows}>{uses.map((use) => <Link href={`/items/${use.idName}`} className={`${styles.row} ${styles.listRow}`} key={use.idName}><span>{use.name}</span><Badge>Open</Badge></Link>)}</div> : <div className={uiStyles.empty}>No recipes consume this item.</div>}</CardBody></Card>
    </div>
    <div className={`${styles.grid} ${styles.twoColumns} ${styles.sectionGap}`}>
      <Card><CardHeader title="Market volume" description="Official daily units sold over the selected history window" /><CardBody>{volumeData.length ? <div className={styles.chart}><ResponsiveContainer width="100%" height="100%"><BarChart data={volumeData}><CartesianGrid stroke="var(--border)" strokeOpacity={0.28} vertical={false}/><XAxis dataKey="date" tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} /><YAxis tickFormatter={(value) => formatInteger(BigInt(Math.round(value)), true)} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} width={60}/><Tooltip formatter={(_value, _name, entry) => `${formatInteger(String(entry.payload.exactUnits))} units`} contentStyle={{ background: "var(--card-strong)", border: "1px solid var(--border)", borderRadius: 8 }}/><Bar dataKey="units" fill="var(--chart-2)" radius={[4, 4, 0, 0]}/></BarChart></ResponsiveContainer></div> : <div className={uiStyles.empty}>No volume history is available yet.</div>}{approximateVolumeChart && <Notice>Chart positions are approximate at this scale; hover values show the exact units.</Notice>}</CardBody></Card>
      <Card><CardHeader title="Recent activity" description="Latest market listings, purchases, and delistings" /><CardBody className={uiStyles.tableWrap}>{marketQuery.data?.transactions.length ? <table className={uiStyles.table}><thead><tr><th>Action</th><th>Actor</th><th>Amount</th><th>Unit price</th><th>Time</th></tr></thead><tbody>{marketQuery.data.transactions.slice(0, 20).map((transaction, index) => <tr key={`${transaction.date}-${transaction.actorName}-${index}`}><td><Badge tone={transaction.type === "buy" ? "positive" : transaction.type === "delist" ? "warning" : "neutral"}>{transaction.type}</Badge></td><td>{transaction.actorName}</td><td className={uiStyles.number}><NumberValue value={transaction.amount} /></td><td className={uiStyles.number}><NumberValue value={transaction.price} unit="BC" /></td><td>{new Date(transaction.date).toLocaleString()}</td></tr>)}</tbody></table> : <div className={uiStyles.empty}>No recent market activity is available.</div>}</CardBody></Card>
    </div>
  </>;
}
function Metric({ label, value, meta }: { label: string; value: React.ReactNode; meta: string }) { return <Card><div className={styles.metric}><div className={styles.metricLabel}>{label}</div><div className={styles.metricValue}>{value}</div><div className={styles.metricMeta}>{meta}</div></div></Card>; }
